replicaCount: 1

image:
  repository: ghcr.io/95ajm/demo-pipeline
  pullPolicy: IfNotPresent
  tag: "f179ea120e56aa23879e7b30aa920d2ebb068515"

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}