name: CI

on:
  push:
    branches: [main]

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  test:
    needs: lint
    uses: ./.github/workflows/test.yml

  build:
    needs: test
    uses: ./.github/workflows/build.yml
    permissions:
      contents: read
      packages: write

  deploy:
    needs: build
    uses: ./.github/workflows/cd.yml
    with:
      image-tag: ${{ needs.build.outputs.image-tag }}
    secrets: inherit
    permissions:
      contents: write